services:
  postgres:
    image: postgres:14
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: url_shortener_backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/url_shortener"
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pgdata:
